import{a as q,S as B,i as c}from"./assets/vendor-DxEWe7lX.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const $="50361154-ffd6605c63a72c4acdaa235b2",x="https://pixabay.com/api/";async function f(i,o=1){const r={key:$,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await q.get(x,{params:r})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),E=new B(".gallery a",{captionsData:"alt",captionDelay:250});function g(i){const o=i.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:a,comments:w,downloads:S})=>`<li class="gallery-item">
           <a href="${n}">
             <img src="${r}" alt="${e}" width="400px" height="250px"/>
           </a>
           <div class="info">
             <p><b>Likes:</b> ${t}</p>
             <p><b>Views:</b> ${a}</p>
             <p><b>Comments:</b> ${w}</p>
             <p><b>Downloads:</b> ${S}</p>
           </div>
         </li>`).join("");m.insertAdjacentHTML("beforeend",o),E.refresh()}function M(){m.innerHTML=""}function b(){h.classList.add("visible")}function l(){h.classList.remove("visible")}function L(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}const v=document.querySelector(".form"),R=v.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let u="",s=1,p=0;v.addEventListener("submit",async i=>{i.preventDefault();const o=R.value.trim();if(!o){c.warning({message:"Будь ласка, введіть пошуковий запит.",position:"topRight"});return}u=o,s=1,M(),d(),b();try{const r=await f(u,s);if(p=r.totalHits,l(),!r.hits.length){c.info({message:"На жаль, зображень за вашим запитом не знайдено.",position:"topRight"});return}g(r.hits),p>s*15&&L()}catch(r){l(),c.error({message:"Сталася помилка. Спробуйте пізніше.",position:"topRight"}),console.error(r)}});O.addEventListener("click",async()=>{s++,b(),d();try{const i=await f(u,s);g(i.hits),l();const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*4,behavior:"smooth"}),s*15>=p?(c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d()):L()}catch(i){l(),c.error({message:"Сталася помилка при завантаженні наступної сторінки.",position:"topRight"}),console.error(i)}});
//# sourceMappingURL=index.js.map
